version: "3.6"

services:
  frontend:
    container_name: frontend
    build: ./frontend
    networks:
      - docker-network
    ports:
      - "80:4321"
    environment:
      - API_URL=http://backend
      # make sure that the port is the same
      # as the one in the backend environment
      # variable (PORT)
      - API_PORT=5000
    depends_on:
      - backend

  backend:
    container_name: backend
    build: ./backend
    networks:
      - docker-network
    volumes:
      # make a volume for the database
      # so that the data is persisted
      # and not lost when the container
      # is stopped. also allows for easy
      # backups
      - ./database/network.sqlite:/app/tllabra/network.sqlite
    environment:
      # make sure that this has the same value
      # As the one in the frontend environment
      # variable (API_PORT)
      - PORT=5000
      # choose the admin credentials here
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=admin

networks:
  docker-network:
